language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
      env:
      - COMPILER=clang++
      - CPPFLAGS="-I /usr/include/c++/v1"
    - os: osx
      compiler: clang
      env: COMPILER=clang++
      # GCC is linked to clang, so we don't need to compile twice for same compiler/platform

before_script:
  - echo $TRAVIS_OS_NAME
  
  - mkdir build
  - cd build
  - cmake ../
  
script: make
